import { useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { Activity, AlertTriangle, BarChart3, BriefcaseMedical, ChevronRight, Clock3, FileText, HeartPulse, Home, Layers3, ListChecks, Search, Users, X } from 'lucide-react';
import { getCases, getCase } from '../../services/caseApi';
import type { CaseDetail, CaseRecord } from '../../types/api';
import { DataState } from '../../components/ui/DataState';
import { StatusBadge } from '../../components/ui/StatusBadge';
import './HubAgentPage.css';

const tabs=['Overview','Payer & Plan','Clinical','Barriers & Insights','Actions','Documents'];
const tabSlug=(s:string)=>s.toLowerCase().replace(/ /g,'-').replace('&-','');
function useCases(){const [items,setItems]=useState<CaseRecord[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=()=>{setLoading(true);setError('');getCases().then(x=>setItems(x.items??[])).catch(e=>setError(e.message)).finally(()=>setLoading(false));};useEffect(load,[]);return {items,loading,error,retry:load};}
export function HubAgentPage(){const {caseId}=useParams(),location=useLocation(),navigate=useNavigate(),{items,loading,error,retry}=useCases();const [selected,setSelected]=useState<CaseRecord|null>(null);const [detail,setDetail]=useState<CaseDetail|null>(null);const [detailError,setDetailError]=useState('');const [query,setQuery]=useState('');
 const activeCase=useMemo(()=>items.find(c=>String(c.case_id)===caseId||c.case_number===caseId)||selected||items[0]||null,[items,caseId,selected]);
 useEffect(()=>{if(activeCase){setSelected(activeCase);getCase(String(activeCase.case_id)).then(setDetail).catch(e=>setDetailError(e.message));}},[activeCase?.case_id]);
 const currentTab=tabs.find(t=>location.pathname.includes(`/${tabSlug(t)}`))||'Overview';const goTab=(tab:string)=>{if(!activeCase)return;const base=`/cases/${activeCase.case_id}`;navigate(tab==='Overview'?base:`${base}/${tabSlug(tab)}`);};
 const filtered=items.filter(c=>`${c.case_number} ${c.patient_token??''} ${c.payer_name??''} ${c.drug_name??''}`.toLowerCase().includes(query.toLowerCase()));
 const critical=items.filter(c=>c.risk_band?.toLowerCase()==='critical'||(c.bscore??0)>=70).length;const overdue=items.filter(c=>c.sla_due_at&&new Date(c.sla_due_at)<new Date()).length;
 return <div className="hub-workspace"><aside className="rail">{[Home,ListChecks,Clock3,Users,Layers3,Activity].map((Icon,i)=><button key={i} className={i===0?'rail-active':''} aria-label={['Home','Cases','SLA','Team','Policies','Activity'][i]}><Icon size={20}/></button>)}</aside><main className="hub-main"><section className="metrics-strip"><Metric icon={<Users/>} label="Active Cases" value={loading?'—':items.length} sub="Assigned"/><Metric icon={<AlertTriangle/>} label="SLA Approaching" value={loading?'—':items.filter(c=>c.sla_due_at&&new Date(c.sla_due_at)>new Date()&&new Date(c.sla_due_at).getTime()-Date.now()<48*3600000).length} sub="Due soon" tone="amber"/><Metric icon={<Clock3/>} label="SLA Overdue" value={loading?'—':overdue} sub="Due past" tone="red"/><Metric icon={<AlertTriangle/>} label="Critical Risk Queue" value={loading?'—':critical} sub="High risk" tone="red"/></section>
 <div className="hub-layout"><aside className="queue panel"><div className="panel-heading"><h2>Work Queue <span>{items.length?`(${Math.round(items.filter(c=>c.current_state!=='CLOSED').length/items.length*100)}%)`:''}</span></h2><span className="count-pill">{items.length}</span></div><div className="queue-filters"><label>Risk Band<select><option>All</option><option>Critical</option><option>High</option></select></label><label>SLA Urgency<select><option>Due soon</option><option>Any</option></select></label><label className="queue-search"><Search size={14}/><input placeholder="Search cases" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="case-list"><DataState loading={loading} error={error} onRetry={retry} hasData={filtered.length>0} empty="No assigned cases found.">{filtered.map(c=><button key={c.case_id} className={`case-card ${activeCase?.case_id===c.case_id?'case-selected':''}`} onClick={()=>{setSelected(c);navigate(`/cases/${c.case_id}${currentTab==='Overview'?'':`/${tabSlug(currentTab)}`}`);}}><div className="case-top"><strong>#{c.case_number}</strong><span className="dots">•••</span></div><p>Patient: <b>{c.patient_token||'—'}</b></p><p>State: <StatusBadge value={c.current_state}/></p><p>Drug: {c.drug_name||'—'}</p><p>Payer: {c.payer_name||'—'}</p><p>SLA: {formatSla(c.sla_due_at)}</p><p>Risk Tag: <StatusBadge value={c.risk_band||bandFromScore(c.bscore)}/></p><p>Action: {c.action_required||'No action recorded'}</p></button>)}</DataState></div></aside>
 <section className="case-center"><DataState loading={loading} error={error} onRetry={retry} hasData={!!activeCase} empty="Select a case from the queue when cases are available.">{activeCase&&<><header className="case-summary panel"><div className="case-summary-main"><BriefcaseMedical className="accent-icon" size={23}/><div><h1>#{activeCase.case_number} <StatusBadge value={activeCase.risk_band||bandFromScore(activeCase.bscore)}/></h1><p>Drug: {activeCase.drug_name||'—'} <i/> Payer: {activeCase.payer_name||'—'} <i/> Member ID: {activeCase.patient_token||'—'}</p></div></div><div className="sla-block"><Clock3 className="accent-icon"/><div><small>SLA Remaining</small><strong>{formatSla(activeCase.sla_due_at)}</strong></div><StatusBadge value={slaState(activeCase.sla_due_at)}/></div></header><nav className="case-tabs panel">{tabs.map(t=><button key={t} className={t===currentTab?'tab-active':''} onClick={()=>goTab(t)}>{t}</button>)}</nav><CaseTab tab={currentTab} item={activeCase} detail={detail} detailError={detailError}/></>}</DataState></section>
 <aside className="case-aside"><section className="panel case-status"><h2>Case Status <StatusBadge value={activeCase?.current_state}/></h2><Info label="Created" value={dateTime(activeCase?.created_at)}/><Info label="Last Updated" value={dateTime(activeCase?.updated_at)}/><Info label="Assigned To" value={activeCase?.assigned_to||activeCase?.owner_role||'Unassigned'}/><Info label="Payer" value={activeCase?.payer_name}/><Info label="Drug" value={activeCase?.drug_name}/><Info label="Patient ID" value={activeCase?.patient_token}/></section><section className="panel sla-card"><div><Clock3/><h2>SLA</h2></div><strong>{formatSla(activeCase?.sla_due_at)}</strong><StatusBadge value={slaState(activeCase?.sla_due_at)}/></section><section className="panel timeline"><h2><Clock3 size={18}/> Timeline <span>{detail?.timeline.length??0}</span></h2>{detail?.timeline?.length?detail.timeline.slice(0,5).map((e,i)=><p key={i}><i/>{String(e.new_state??e.event??'Updated').replace(/_/g,' ')} <small>{dateTime(String(e.changed_at??''))}</small></p>):<p className="muted">No case history recorded.</p>}</section><div className="case-actions"><button className="action-button"><X/>Close Case</button><button className="action-button danger"><AlertTriangle/>Escalate</button><button className="action-button warning"><HeartPulse/>Override</button></div></aside></div></main></div>}
function Metric({icon,label,value,sub,tone=''}:{icon:React.ReactNode;label:string;value:number|string;sub:string;tone?:string}){return <div className="metric"><span className={`metric-icon ${tone}`}>{icon}</span><div><small>{label}</small><b>{value}</b><em>{sub}</em></div></div>}
function Info({label,value}:{label:string;value:unknown}){return <p className="info-row"><span>{label}</span><strong>{value==null||value===''?'—':String(value)}</strong></p>}
function CaseTab({tab,item,detail,detailError}:{tab:string;item:CaseRecord;detail:CaseDetail|null;detailError:string}){if(tab==='Payer & Plan')return <div className="tab-grid"><Panel title="Payer Information" icon={<BriefcaseMedical/>}><Info label="Payer" value={item.payer_name}/><Info label="Payer ID" value={item.payer_id}/><Info label="Plan Type" value={item.plan_type}/><EmptySchema text="Plan benefits and payer contact details are not present in the supplied schema."/></Panel><Panel title="Patient Plan Details" icon={<Users/>}><Info label="Member ID" value={item.patient_token}/><Info label="Territory" value={item.territory}/><Info label="Case Owner" value={item.assigned_to||item.owner_role}/></Panel><Panel title="Policy Rules" icon={<FileText/>}><EmptySchema text="No matching payer rule pack is linked to this case."/></Panel></div>;
 if(tab==='Clinical')return <div className="tab-grid"><Panel title="Clinical Summary" icon={<HeartPulse/>}><Info label="Diagnosis" value={item.diagnosis_name}/><Info label="Diagnosis Code" value={item.diagnosis_code}/><Info label="Drug" value={item.drug_name}/><Info label="Drug ID" value={item.drug_id}/><Info label="Patient Token" value={item.patient_token}/>{detail?.prescriptions?.length?detail.prescriptions.map((p,i)=><Info key={i} label={`Prescription ${i+1}`} value={`${p.quantity??'—'} units · ${p.days_supply??'—'} days supply`}/>):<EmptySchema text="No prescription details are linked to this case."/>}</Panel><Panel title="Current Assessment" icon={<Activity/>}>{detail?.assessment?<><Info label="Risk Score" value={detail.assessment.risk_score}/><Info label="B.Score" value={detail.assessment.bscore}/><Info label="Confidence" value={detail.assessment.confidence}/><Info label="Model Version" value={detail.assessment.model_version}/></>:<EmptySchema text={detailError||'No current assessment is available.'}/>}</Panel></div>;
 if(tab==='Barriers & Insights')return <div className="tab-grid"><Panel title="Risk Assessment" icon={<BarChart3/>}><div className="risk-score"><strong>{item.bscore??'—'}</strong><span>/ 100</span></div><StatusBadge value={item.risk_band||bandFromScore(item.bscore)}/><p>{item.executive_summary||'No assessment summary is available for this case.'}</p></Panel><Panel title="Predicted Barriers" icon={<AlertTriangle/>}>{(detail?.barriers?.length?detail.barriers:toArray(item.predicted_barriers)).length?toArray(detail?.barriers?.length?detail.barriers:item.predicted_barriers).map((v,i)=><div key={i} className="data-row"><span>{typeof v==='string'?v:JSON.stringify(v)}</span><ChevronRight size={16}/></div>):<EmptySchema text="No predicted barriers are recorded."/>}</Panel><Panel title="Recommendations" icon={<ListChecks/>}>{detail?.insights?.length?detail.insights.map((x,i)=><p key={i}>{String(x.recommendations??x.executive_summary??'Insight available')}</p>):<EmptySchema text="No recommendations are available."/>}</Panel></div>;
 if(tab==='Actions')return <Panel title="Assignments & Required Actions" icon={<ListChecks/>}>{detail?.assignments?.length?<div className="table-wrap"><table><thead><tr><th>Role</th><th>Assigned To</th><th>Action Required</th><th>SLA Due</th><th>Status</th></tr></thead><tbody>{detail.assignments.map((a,i)=><tr key={i}><td>{String(a.role_type??'—')}</td><td>{String(a.user_name??'Unassigned')}</td><td>{String(a.action_required??'—')}</td><td>{dateTime(String(a.sla_due_at??''))}</td><td><StatusBadge value={String(a.assignment_status??'—')}/></td></tr>)}</tbody></table></div>:<EmptySchema text="No assignment actions are recorded for this case."/>}</Panel>;
 if(tab==='Documents')return <Panel title="Case Documents" icon={<FileText/>}>{detail?.documents?.length?<div className="data-state">Document records returned from the connected API.</div>:<EmptySchema text="The supplied database schema does not define a case document table, so no document rows can be shown."/>}</Panel>;
 return <><div className="tab-grid overview-grid"><Panel title="Case Intelligence" icon={<Activity/>}><div className="score-card"><div><small>Risk Score</small><strong>{item.bscore??'—'}<small>/100</small></strong></div><StatusBadge value={item.risk_band||bandFromScore(item.bscore)}/></div><Info label="Current State" value={item.current_state}/><Info label="Confidence" value={percent(item.confidence)}/><Info label="Assigned Owner" value={item.assigned_to||item.owner_role}/><Info label="Drug" value={item.drug_name}/><Info label="Payer" value={item.payer_name}/></Panel><Panel title="Required Actions" icon={<ListChecks/>}>{detail?.assignments?.length?detail.assignments.slice(0,3).map((a,i)=><div className="action-row" key={i}><StatusBadge value={String(a.assignment_status??'ASSIGNED')}/><div><b>{String(a.action_required??'Follow up on case')}</b><span>Owner: {String(a.user_name??a.role_type??'Unassigned')}</span></div></div>):<EmptySchema text="No required actions recorded."/>}</Panel></div><Panel title="AI Generated Executive Summary" icon={<Activity/>}>{item.executive_summary||'No case insight summary is available.'}</Panel><Panel title="Assessment & Barriers" icon={<AlertTriangle/>}><div className="three-cards"><div><b>Risk band</b><p><StatusBadge value={item.risk_band||bandFromScore(item.bscore)}/></p></div><div><b>Assessment score</b><p>{item.bscore??'—'}</p></div><div><b>Predicted barriers</b><p>{toArray(item.predicted_barriers).length||'—'} recorded</p></div></div></Panel></>}
function Panel({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="panel content-panel"><header><span>{icon}</span><h2>{title}</h2><button aria-label={`${title} options`}>•••</button></header>{children}</section>}
function EmptySchema({text}:{text:string}){return <div className="inline-empty">{text}</div>}
function formatSla(value:string|null|undefined){if(!value)return 'Not set';const ms=new Date(value).getTime()-Date.now();if(Number.isNaN(ms))return new Date(value).toLocaleString();if(ms<0)return 'Overdue';const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000);return `${h}h ${m}m`;}
function slaState(value:string|null|undefined){if(!value)return 'Not set';const diff=new Date(value).getTime()-Date.now();return diff<0?'Overdue':diff<48*3600000?'Approaching':'On track';}
function bandFromScore(n:number|null|undefined){return n==null?'Unscored':n>=70?'High Risk':n>=40?'Medium':'Low';}
function dateTime(s:string|null|undefined){return s?new Date(s).toLocaleString(undefined,{month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';}
function percent(n:number|null|undefined){return n==null?'—':`${Math.round(n*100)}%`;}
function toArray(v:unknown):unknown[]{if(Array.isArray(v))return v;if(typeof v==='string'){try{const j=JSON.parse(v);return Array.isArray(j)?j:[]}catch{return []}}return [];}
